version: '3'

volumes:
    postgres_data: {}

services:

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    command: ["sh", "-c", "python manage.py migrate && supervisord -n"]

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - 8090:80
    depends_on:
      - django

  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data